services:
  frontend:
    build:
      context: ./DockerFrontend/.
    image: kashiiitech/frontend
    container_name: frontend
    ports:
      - 1234:80

  api:
    build: 
      # context: ./BackendApii/.
      dockerfile: ./BackendApii/Dockerfile
    image: kashiiitech/api
    container_name: api
    ports:
      - 7176:8080

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    command: /opt/mssql/bin/sqlservr
    container_name: database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Dometrain#123
    ports:
      - 1433:1433

  database-seed:
    depends_on: [ database ]
    build: 
      context: Database/
      dockerfile: Dockerfile
    container_name: database-seed